// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ztnsgmyjtnltwfwazavf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0bnNnbXlqdG5sdHdmd2F6YXZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MjYyMTEsImV4cCI6MjA3MTIwMjIxMX0.EQjwqf4-8ciW1FXNEhJziRDmQHNJ83NqqiXe7ysNXXU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});